[package]
name = "transaction-pool-bundle-ext"
version.workspace = true
edition.workspace = true

[dependencies]
reth = { workspace = true }
reth-eth-wire-types = { workspace = true }
reth-primitives = { workspace = true }
reth-transaction-pool = { workspace = true }
alloy-primitives = { workspace = true, default-features = false }
alloy-rpc-types-beacon = { workspace = true, features = ["ssz"] }
alloy-eips = { workspace = true }


tokio = { workspace = true }
